version: "2" 
services:
  jenkins:
    image: jenkins:1.642.1
    volumes:
      - ../nodes/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - asterix

  jenkins-slave:
    image: ceejatec/asterix-centos7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../nodes/as-shared:/home/couchbase/shared
      - ../nodes/jenkins-slave:/home/couchbase/jenkins
    networks:
      - asterix

  nc1:
    image: ceejatec/asterix-centos7
    volumes:
      - ../nodes/as-shared:/home/couchbase/shared
    ports:
      - "2221:22"
      - "19001:19001"
      - "19002:19002"
      - "19003:19002"
    networks:
      - asterix

  nc2:
    image: ceejatec/asterix-centos7
    volumes:
      - ../nodes/as-shared:/home/couchbase/shared
    ports:
      - "2222:22"
    networks:
      - asterix

  nc3:
    image: ceejatec/asterix-centos7
    volumes:
      - ../nodes/as-shared:/home/couchbase/shared
    ports:
      - "2223:22"
    networks:
      - asterix

  nc4:
    image: ceejatec/asterix-centos7
    volumes:
      - ../nodes/as-shared:/home/couchbase/shared
    ports:
      - "2224:22"
    networks:
      - asterix

  couchbase1.host:
    image: couchbase
    networks:
      - asterix

  couchbase2.host:
    image: couchbase
    networks:
      - asterix

  couchbase3.host:
    image: couchbase
    ports:
      - 8091:8091
      - 8092:8092 
      - 8093:8093 
      - 11210:11210
    networks:
      - asterix


networks:
  asterix:

